[2023-07-07 23:13:39] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-07-07 23:13:39] [DEBUG   ] discord.client: on_guild_join has successfully been registered as an event
[2023-07-07 23:13:39] [DEBUG   ] discord.client: on_member_join has successfully been registered as an event
[2023-07-07 23:13:39] [INFO    ] discord.client: logging in using static token
[2023-07-07 23:13:41] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 947256d1b978d364fe9355cea03f8e17).
[2023-07-07 23:13:43] [INFO    ] discord: Logged in as ajoke#0521 (ID: 1123604895300329502).
[2023-07-07 23:22:53] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-07-07 23:22:53] [DEBUG   ] discord.client: on_guild_join has successfully been registered as an event
[2023-07-07 23:22:53] [DEBUG   ] discord.client: on_member_join has successfully been registered as an event
[2023-07-07 23:22:53] [INFO    ] discord.client: logging in using static token
[2023-07-07 23:22:54] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e01dc384ffb7730d3b03410536a6e071).
[2023-07-07 23:22:56] [INFO    ] discord: Logged in as ajoke#0521 (ID: 1123604895300329502).
[2023-07-07 23:24:13] [ERROR   ] discord.client: Ignoring exception in on_guild_join
Traceback (most recent call last):
  File "C:\Users\Victor Momodu\Documents\Programming\Software Engineering\Code\DiscordManager\.venv\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\Victor Momodu\Documents\Programming\Software Engineering\Code\DiscordManager\event_listener.py", line 46, in on_guild_join
    logger.info(f"{guild.name}-{guild-id} has just been added.")
TypeError: unsupported operand type(s) for -: 'Guild' and 'builtin_function_or_method'
[2023-07-07 23:27:11] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-07-07 23:27:11] [DEBUG   ] discord.client: on_guild_join has successfully been registered as an event
[2023-07-07 23:27:11] [DEBUG   ] discord.client: on_member_join has successfully been registered as an event
[2023-07-07 23:27:11] [INFO    ] discord.client: logging in using static token
[2023-07-07 23:27:13] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 6fe7d7697a71c39d4261042761643c2d).
[2023-07-07 23:27:15] [INFO    ] discord: Logged in as ajoke#0521 (ID: 1123604895300329502).
[2023-07-07 23:27:27] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command leave
Traceback (most recent call last):
  File "C:\Users\Victor Momodu\Documents\Programming\Software Engineering\Code\DiscordManager\.venv\lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\Users\Victor Momodu\Documents\Programming\Software Engineering\Code\DiscordManager\event_listener.py", line 58, in leave
    await ctx.send("Leaving server...")
  File "C:\Users\Victor Momodu\Documents\Programming\Software Engineering\Code\DiscordManager\.venv\lib\site-packages\discord\ext\commands\context.py", line 1024, in send
    return await super().send(
  File "C:\Users\Victor Momodu\Documents\Programming\Software Engineering\Code\DiscordManager\.venv\lib\site-packages\discord\abc.py", line 1562, in send
    data = await state.http.send_message(channel.id, params=params)
  File "C:\Users\Victor Momodu\Documents\Programming\Software Engineering\Code\DiscordManager\.venv\lib\site-packages\discord\http.py", line 739, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Victor Momodu\Documents\Programming\Software Engineering\Code\DiscordManager\.venv\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Victor Momodu\Documents\Programming\Software Engineering\Code\DiscordManager\.venv\lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Victor Momodu\Documents\Programming\Software Engineering\Code\DiscordManager\.venv\lib\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 50001): Missing Access
[2023-07-07 23:28:13] [DEBUG   ] discord.client: on_ready has successfully been registered as an event
[2023-07-07 23:28:13] [DEBUG   ] discord.client: on_guild_join has successfully been registered as an event
[2023-07-07 23:28:13] [DEBUG   ] discord.client: on_member_join has successfully been registered as an event
[2023-07-07 23:28:13] [INFO    ] discord.client: logging in using static token
[2023-07-07 23:28:15] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c1b01e93ba8e830d94b933a1c1b73a13).
[2023-07-07 23:28:17] [INFO    ] discord: Logged in as ajoke#0521 (ID: 1123604895300329502).
[2023-07-07 23:29:04] [INFO    ] discord: Test Server-1124338606140563629 has just been added.
[2023-07-07 23:29:43] [INFO    ] discord: Stopped bot
[2023-07-07 23:29:43] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command stop
Traceback (most recent call last):
  File "C:\Users\Victor Momodu\Documents\Programming\Software Engineering\Code\DiscordManager\.venv\lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\Users\Victor Momodu\Documents\Programming\Software Engineering\Code\DiscordManager\event_listener.py", line 67, in stop
    await bot.logout()
AttributeError: 'Bot' object has no attribute 'logout'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Victor Momodu\Documents\Programming\Software Engineering\Code\DiscordManager\.venv\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Victor Momodu\Documents\Programming\Software Engineering\Code\DiscordManager\.venv\lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\Victor Momodu\Documents\Programming\Software Engineering\Code\DiscordManager\.venv\lib\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Bot' object has no attribute 'logout'
